/**
 * Guided-onboard doc scaffolder (Epic #3438 Story #3519).
 *
 * Detects which of the project's configured `project.docsContextFiles` are
 * absent under the resolved docs root, and — on acceptance — scaffolds a stub
 * for each missing file. Stubs are seeded from a dedicated template under
 * `.agents/templates/docs/<name>` when one ships; otherwise a generic
 * placeholder stub is written so the mandatory-read never resolves to a
 * missing file.
 *
 * The detection pass is side-effect free: callers can preview the missing set
 * (`scaffoldDocs({ write: false })`) before deciding whether to scaffold.
 *
 * @module lib/onboard/scaffold-docs
 */

import fsDefault from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { getPaths, resolveConfig } from '../config-resolver.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
// scripts/lib/onboard/ → scripts/lib/ → scripts/ → .agents/
const AGENT_ROOT = path.resolve(__dirname, '../../..');
const DOCS_TEMPLATE_DIR = path.join(AGENT_ROOT, 'templates', 'docs');

/**
 * Deterministic marker written into every scaffolded stub. The `/plan`
 * first-run preflight (and any tooling that wants to detect unedited stubs)
 * keys off this exact string — do not change it without a hard cutover.
 *
 * @type {string}
 */
export const STUB_MARKER = '<!-- MANDREL:STUB -->';

/**
 * Build the generic placeholder stub for a docsContextFile that has no
 * dedicated template. Derives a human-readable title from the filename.
 *
 * @param {string} fileName - e.g. `data-dictionary.md`
 * @returns {string}
 */
function genericStub(fileName) {
  const base = fileName.replace(/\.[^.]+$/, '');
  const title = base
    .split(/[-_]/)
    .filter(Boolean)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
  return (
    `${STUB_MARKER}\n` +
    `# ${title}\n\n` +
    '> **Stub generated by `mandrel init`.** This file is one of the\n' +
    '> `project.docsContextFiles` mandatory-reads — agents load it before\n' +
    '> every task. Replace this placeholder with real content.\n'
  );
}

/**
 * Read the dedicated template body for a docsContextFile, or fall back to the
 * generic stub when no template ships for that name. Either path prepends the
 * {@link STUB_MARKER} so the `/plan` first-run preflight can detect un-edited
 * stubs regardless of whether a dedicated template was used.
 *
 * @param {string} fileName
 * @param {import('node:fs')} fsImpl
 * @returns {string}
 */
function stubContentFor(fileName, fsImpl) {
  const templatePath = path.join(DOCS_TEMPLATE_DIR, fileName);
  if (fsImpl.existsSync(templatePath)) {
    const body = fsImpl.readFileSync(templatePath, 'utf8');
    // Prepend the marker only when absent (idempotent; the template files
    // themselves are kept marker-free so they read cleanly as documentation).
    return body.startsWith(STUB_MARKER) ? body : `${STUB_MARKER}\n${body}`;
  }
  return genericStub(fileName);
}

/**
 * Detect missing docsContextFiles and, on acceptance, scaffold stubs.
 *
 * @param {object} [opts]
 * @param {string} [opts.root] - Project root to resolve config + docs root
 *   against. Defaults to the resolver's `PROJECT_ROOT`.
 * @param {string[]} [opts.docsContextFiles] - Override the configured list
 *   (primarily for tests). Falls back to `project.docsContextFiles`.
 * @param {string} [opts.docsRoot] - Override the resolved docs-root directory
 *   name (relative to `root`). Falls back to `project.paths.docsRoot`.
 * @param {boolean} [opts.write=true] - When `false`, only detect (no files are
 *   created). When `true` (acceptance), scaffold each missing file.
 * @param {import('node:fs')} [opts.fs] - Injectable fs implementation.
 * @returns {{
 *   docsRoot: string,
 *   docsContextFiles: string[],
 *   missing: string[],
 *   present: string[],
 *   created: string[],
 * }}
 */
export function scaffoldDocs(opts = {}) {
  const fsImpl = opts.fs ?? fsDefault;
  const write = opts.write !== false;

  const config = resolveConfig({ cwd: opts.root, ctx: { fs: fsImpl } });
  const projectRoot = path.resolve(opts.root ?? process.cwd());

  const docsContextFiles =
    opts.docsContextFiles ?? config.project.docsContextFiles ?? [];
  const docsRootName = opts.docsRoot ?? getPaths(config).docsRoot;
  const docsRootAbs = path.resolve(projectRoot, docsRootName);

  const present = [];
  const missing = [];
  for (const fileName of docsContextFiles) {
    const target = path.join(docsRootAbs, fileName);
    if (fsImpl.existsSync(target)) {
      present.push(fileName);
    } else {
      missing.push(fileName);
    }
  }

  const created = [];
  if (write && missing.length > 0) {
    fsImpl.mkdirSync(docsRootAbs, { recursive: true });
    for (const fileName of missing) {
      const target = path.join(docsRootAbs, fileName);
      // Guard against nested paths whose parent dir is absent.
      fsImpl.mkdirSync(path.dirname(target), { recursive: true });
      fsImpl.writeFileSync(target, stubContentFor(fileName, fsImpl), 'utf8');
      created.push(fileName);
    }
  }

  return {
    docsRoot: docsRootAbs,
    docsContextFiles,
    missing,
    present,
    created,
  };
}
