/**
 * kinds/duplication.js — per-kind module for the code-duplication (DRY)
 * baseline (Story #3664).
 *
 * Row shape: `{ path, duplicatedLines, totalLines, percentage }`. Each row
 * records how much of a single source file is copy-paste duplication, as
 * reported by a clone detector (jscpd). `percentage` is the per-file
 * duplication ratio in [0, 100]; `duplicatedLines` / `totalLines` are the
 * raw line counts the percentage derives from, kept so the whole-repo
 * rollup can recompute an exact aggregate ratio rather than averaging
 * per-file percentages (which would over-weight small files).
 *
 * Lower duplication is better, so the gate's floor direction is `lte`
 * (see `check-baselines/phases/floors.js#axisDirection`). New paths land
 * in the `additions` bucket (Story #2012); removed paths count as
 * improvements when they carried any duplication — the file is gone, so
 * its prior debt is gone too.
 *
 * `kernelVersion()` returns a static in-repo semver — the duplication
 * scorer is the in-repo scan + rollup contract (the jscpd output is
 * normalised before it reaches this module), so there is no upstream
 * library version to track the way CRAP/MI track `typhonjs-escomplex`.
 * Bump the version passed to `makeBaselineKind` whenever the row shape or
 * rollup math changes. Scaffold is generated by `makeBaselineKind`
 * (Story #3983).
 */

import { canonicalise } from '../path-canon.js';
import { makeBaselineKind } from './kind-factory.js';

export const name = 'duplication';
export const keyField = 'path';

export function projectRow(row) {
  const duplicatedLines = Number(row.duplicatedLines ?? 0);
  const totalLines = Number(row.totalLines ?? 0);
  const percentage =
    row.percentage === undefined || row.percentage === null
      ? computePercentage(duplicatedLines, totalLines)
      : Number(row.percentage);
  return {
    path: canonicalise(row.path ?? row.file),
    duplicatedLines,
    totalLines,
    percentage: roundTo2(percentage),
  };
}

/**
 * Exact aggregate duplication ratio: total duplicated lines / total lines
 * across the row set, expressed as a percentage. Averaging per-file
 * percentages would over-weight small files, so the rollup recomputes from
 * the raw line counts each row carries.
 */
function aggregate(rows) {
  if (!rows || rows.length === 0) {
    return {
      percentage: 0,
      duplicatedLines: 0,
      totalLines: 0,
      filesWithDuplication: 0,
    };
  }
  let duplicatedLines = 0;
  let totalLines = 0;
  let filesWithDuplication = 0;
  for (const r of rows) {
    duplicatedLines += r.duplicatedLines ?? 0;
    totalLines += r.totalLines ?? 0;
    if ((r.duplicatedLines ?? 0) > 0) filesWithDuplication += 1;
  }
  return {
    percentage: roundTo2(computePercentage(duplicatedLines, totalLines)),
    duplicatedLines,
    totalLines,
    filesWithDuplication,
  };
}

function computePercentage(duplicatedLines, totalLines) {
  if (!Number.isFinite(totalLines) || totalLines <= 0) return 0;
  return (duplicatedLines / totalLines) * 100;
}

function roundTo2(value) {
  if (!Number.isFinite(value)) return 0;
  return Number(value.toFixed(2));
}

export const {
  kernelVersion,
  sortRows,
  rollup,
  compare,
  applyEpsilon,
  mergeRows,
} = makeBaselineKind({
  keyField,
  kernelVersion: '1.0.0',
  axes: ['percentage'],
  betterWhen: 'lower',
  aggregate,
  missingBasePolicy: 'addition',
  removedRowPolicy: {
    kind: 'improvement-when',
    when: (b) => (b.percentage ?? 0) > 0,
  },
});
