/**
 * kinds/lighthouse.js — per-kind module for the Lighthouse audit baseline
 * (Story #1891). Row shape: `{ route, performance, accessibility,
 * bestPractices, seo }`. The key field is `route` (a path-like string that
 * still passes the path-canon checks for absolute / `..` rejection).
 *
 * Higher score = better. New routes inherit a base of 100 for each axis
 * (so lower scores register as regressions — a new route must meet the
 * bar); dropped routes inherit a head of 100 (so a higher base registers
 * as an improvement). Unlike the file-derived kinds, compare emits no
 * `additions` bucket. Scaffold is generated by `makeBaselineKind`
 * (Story #3983).
 */

import { canonicalise } from '../path-canon.js';
import { makeBaselineKind } from './kind-factory.js';

export const name = 'lighthouse';
export const keyField = 'route';

const LH_AXES = ['performance', 'accessibility', 'bestPractices', 'seo'];

function canonRoute(route) {
  // Routes look like `/`, `/dashboard`, or `pricing` — strip the leading
  // slash so the canonicaliser doesn't see them as absolute paths.
  if (typeof route !== 'string') return canonicalise(route);
  const stripped = route.startsWith('/') ? route.slice(1) : route;
  if (stripped.length === 0) return '/';
  return canonicalise(stripped);
}

export function projectRow(row) {
  return {
    route: canonRoute(row.route),
    performance: Number(row.performance),
    accessibility: Number(row.accessibility),
    bestPractices: Number(row.bestPractices),
    seo: Number(row.seo),
  };
}

function meanOf(rows, axis) {
  let sum = 0;
  for (const r of rows) sum += r[axis] ?? 0;
  return Number((sum / rows.length).toFixed(2));
}

function aggregate(rows) {
  if (!rows || rows.length === 0) {
    return { performance: 0, accessibility: 0, bestPractices: 0, seo: 0 };
  }
  return {
    performance: meanOf(rows, 'performance'),
    accessibility: meanOf(rows, 'accessibility'),
    bestPractices: meanOf(rows, 'bestPractices'),
    seo: meanOf(rows, 'seo'),
  };
}

function perfectLighthouseRow(route) {
  return {
    route,
    performance: 100,
    accessibility: 100,
    bestPractices: 100,
    seo: 100,
  };
}

export const {
  kernelVersion,
  sortRows,
  rollup,
  compare,
  applyEpsilon,
  mergeRows,
} = makeBaselineKind({
  keyField,
  kernelVersion: '1.0.0',
  axes: LH_AXES,
  betterWhen: 'higher',
  aggregate,
  missingBasePolicy: 'perfect',
  removedRowPolicy: { kind: 'perfect-head' },
  perfectRow: perfectLighthouseRow,
});
