/**
 * kinds/maintainability.js — per-kind module for the Maintainability Index
 * (MI) baseline (Story #1891).
 *
 * Row shape: `{ path, mi }`. The legacy baseline shipped a flat `{ path: mi }`
 * map; the v2 envelope arrays each row explicitly so per-row metadata can
 * grow without churning the schema.
 *
 * MI is computed by the in-repo `escomplex-engine` kernel — same upstream
 * dependency family as CRAP — so the kernel version tracks
 * `typhonjs-escomplex` too.
 *
 * Higher MI = better. New paths land in the `additions` bucket
 * (Story #2012 — new files MUST NOT register as regressions); removed
 * paths count as improvements when their MI was non-perfect — the file is
 * gone, so its prior debt is gone too. Scaffold (sortRows / rollup /
 * compare / applyEpsilon / mergeRows) is generated by `makeBaselineKind`
 * (Story #3983).
 */

import { readBaselineAtRef } from '../../baseline-loader.js';
import { loadBaseline } from '../../gates/baseline-store.js';
import { getBaseline } from '../maintainability-baseline-io.js';
import { canonicalise } from '../path-canon.js';
import { percentile } from './_shared-metric.js';
import { kernelVersion as crapKernelVersion } from './crap.js';
import { makeBaselineKind } from './kind-factory.js';

export const name = 'maintainability';
export const keyField = 'path';

/**
 * Files the maintainability scorer cannot measure because `typhonjs-escomplex`
 * (the upstream kernel) parse-fails on syntax the runtime supports but the
 * library has never been updated for. Each entry must carry a one-line reason
 * so a future engine bump can audit the list and drop the exclusion.
 *
 * Story #2467 / Task #2494 — the prior behaviour stored these files with
 * `mi: 0` in `baselines/maintainability.json`, which corrupted the global
 * `min`/p50 rollup and let real regressions hide behind a phantom floor.
 * Excluding them at the scorer makes the absence explicit; the comparator
 * already treats missing-in-baseline new files as `additions` (Story #2012)
 * so re-inclusion is non-breaking once the kernel can score them.
 *
 * Canonicalised POSIX repo-relative paths.
 */
export const MAINTAINABILITY_EXCLUSIONS = Object.freeze(
  new Set([
    // escomplex: "Cannot read properties of undefined (reading 'pattern')" —
    // chokes on modern destructuring / regex-property patterns used in the
    // reconciler's spec walker.
    '.agents/scripts/acceptance-spec-reconciler.js',
    // escomplex: same "pattern" parse failure as acceptance-spec-reconciler;
    // both files share the lifecycle-lint regex-driven scan helpers.
    '.agents/scripts/check-lifecycle-lint.js',
    // escomplex: "traveler[node.type] is not a function" — AST node type the
    // upstream traveler table is missing (top-level await / private fields).
    '.agents/scripts/lib/orchestration/epic-cleanup.js',
    // escomplex: same "traveler[node.type] is not a function" — emitted by
    // the spec-reconciler's `async` operator-comment IIFE.
    '.agents/scripts/lib/orchestration/epic-spec-reconciler-ops.js',
    // escomplex: "this[node.callee.type] is not a function" — the cyclomatic
    // visitor lacks a handler for one of the quality-watch CLI's call shapes.
    '.agents/scripts/quality-watch.js',
    // escomplex: "Cannot read properties of undefined (reading 'pattern')" —
    // same family as acceptance-spec-reconciler. The audit recheck CLI uses
    // the same regex-property scan helpers.
    '.agents/scripts/epic-audit-recheck.js',
    // escomplex: parse-fails (MI=0) on the spec-freshness phase's optional-
    // chained destructuring fallthrough. Same upstream family as the other
    // "pattern" / destructuring failures; carve-out so the phase split of
    // epic-plan-spec doesn't poison the global rollup.
    '.agents/scripts/lib/orchestration/epic-plan-spec/phases/spec-freshness.js',
    // escomplex: "Cannot read properties of undefined (reading 'pattern')" —
    // the audit-to-stories parser reuses the same regex-property scan
    // patterns as acceptance-spec-reconciler.
    '.agents/scripts/lib/audit-to-stories/parse-audit-md.js',
    // escomplex: same "pattern" parse failure family — BDD scanner and
    // codebase snapshot helpers walk source trees with regex visitors that
    // hit the upstream destructuring bug.
    '.agents/scripts/lib/bdd-scenario-scanner.js',
    '.agents/scripts/lib/codebase-snapshot.js',
    // escomplex: same "pattern" parse failure — the wave-runner tick uses
    // the regex-property destructuring escomplex chokes on.
    '.agents/scripts/lib/wave-runner/tick.js',
    // escomplex: same "pattern" parse failure — exercises the same
    // destructuring shape in a test fixture.
    'tests/scripts/story-close-merge-subject.test.js',
  ]),
);

/**
 * Filter parse-unscorable files out of a rows array. Used by the scorer
 * before envelope assembly so MI=0 phantoms never reach the on-disk
 * baseline. Pure — does not mutate the input.
 *
 * Two layers:
 *   1. Drop rows whose `path` appears in the explicit
 *      `MAINTAINABILITY_EXCLUSIONS` allowlist (documented escomplex
 *      parse-fail families).
 *   2. Defensive backstop — drop any remaining `mi === 0` rows. A real
 *      MI score never reaches 0 for valid code (the escomplex floor for
 *      runnable JS is ~10–20), so `mi === 0` is a reliable signal that
 *      the scorer hit a parse failure the allowlist hasn't caught yet.
 *      Without this backstop, a newly-added file that escomplex can't
 *      parse silently poisons the global min/p50 rollup (Story #2467
 *      precedent). The audit lens flags any allowlist entries it can
 *      now score so the list stays auditable.
 *
 * @template {{path: string, mi?: number}} R
 * @param {R[]} rows
 * @returns {R[]}
 */
export function filterExcludedRows(rows) {
  if (!Array.isArray(rows)) return [];
  return rows.filter(
    (row) => !MAINTAINABILITY_EXCLUSIONS.has(row?.path) && row?.mi !== 0,
  );
}

export function projectRow(row) {
  return {
    path: canonicalise(row.path),
    mi: Number(row.mi),
  };
}

function aggregate(rows) {
  if (!rows || rows.length === 0) return { min: 0, p50: 0, p95: 0 };
  const sorted = [...rows].map((r) => r.mi).sort((a, b) => a - b);
  return {
    min: sorted[0],
    p50: percentile(sorted, 50),
    p95: percentile(sorted, 95),
  };
}

export const {
  kernelVersion,
  sortRows,
  rollup,
  compare,
  applyEpsilon,
  mergeRows,
} = makeBaselineKind({
  keyField,
  // MI and CRAP share the escomplex kernel — pin them together so a drift
  // in either always invalidates both baselines.
  kernelVersion: crapKernelVersion,
  axes: ['mi'],
  betterWhen: 'higher',
  aggregate,
  missingBasePolicy: 'addition',
  removedRowPolicy: {
    kind: 'improvement-when',
    when: (b) => (b.mi ?? 0) < 100,
  },
});

// ---------------------------------------------------------------------------
// CLI-facing pure helpers (Story #1981, Task #1989).
// Hoisted from `.agents/scripts/check-maintainability.js`.
// ---------------------------------------------------------------------------

// Envelope version for the --json parity output. Bump when the report
// shape changes so downstream agent workflows can detect breaks without
// guessing. 1.1.0 — TypeScript support landed in 5.29.0.
export const MI_REPORT_KERNEL_VERSION = '1.1.0';

/**
 * Pure: build the MI parity envelope. Shape matches the CRAP `--json`
 * output: `{ kernelVersion, summary, violations }` sans `fixGuidance`
 * (MI scores don't decompose along the two CRAP axes).
 *
 * @param {Record<string, number>} scores current MI scores keyed by file
 * @param {{
 *   regressions?: number,
 *   newFiles?: number,
 *   improvements?: number,
 *   regressedFiles?: Array<{file: string, current: number, baseline: number, drop: number}>
 * }} stats
 * @param {{ scope?: 'diff' | 'full', diffRef?: string | null }} [scopeInfo]
 */
export function buildMaintainabilityReport(scores, stats, scopeInfo) {
  const total = Object.keys(scores ?? {}).length;
  const violations = (stats?.regressedFiles ?? []).map((r) => ({
    file: r.file,
    current: r.current,
    baseline: r.baseline,
    drop: r.drop,
    kind: 'regression',
  }));
  const scope = scopeInfo?.scope === 'full' ? 'full' : 'diff';
  const diffRef = scope === 'full' ? null : (scopeInfo?.diffRef ?? null);
  return {
    kernelVersion: MI_REPORT_KERNEL_VERSION,
    summary: {
      total,
      regressions: stats?.regressions ?? 0,
      newFiles: stats?.newFiles ?? 0,
      improvements: stats?.improvements ?? 0,
      scope,
      diffRef,
    },
    violations,
  };
}

/** Thin wrapper: delegate to baseline-store with MI-specific defaults. */
export function loadMaintainabilityBaseline({
  baselinePath,
  epicRef,
  readBaseline = getBaseline,
  readAtRef = readBaselineAtRef,
  logger = console,
}) {
  const parsed = loadBaseline({
    baselinePath,
    epicRef,
    readAtRef,
    readFromTree: ({ baselinePath: p }) => readBaseline(p),
    logger,
    label: 'Maintainability',
  });
  // Epic-ref read may return a non-object — coerce to {} so downstream
  // `Object.entries` / `Object.keys` never throws.
  if (epicRef && (parsed === null || typeof parsed !== 'object')) return {};
  // Story #1895: the on-disk baseline switched from the flat
  // `{ path: mi }` map to the canonical envelope shape. Project envelope
  // back to the legacy flat shape so downstream comparators keep working.
  if (
    parsed &&
    typeof parsed === 'object' &&
    !Array.isArray(parsed) &&
    Array.isArray(parsed.rows) &&
    typeof parsed.$schema === 'string'
  ) {
    const flat = {};
    for (const row of parsed.rows) {
      if (row && typeof row.path === 'string' && typeof row.mi === 'number') {
        flat[row.path] = row.mi;
      }
    }
    return flat;
  }
  return parsed;
}
