/**
 * kinds/mutation.js — per-kind module for the mutation-testing baseline
 * (Story #1891). Row shape: `{ path, score, killed, survived }`. Rollup
 * carries score/killed/survived/noCoverage. Stryker is the upstream
 * kernel; we pin a static version until a Mandrel-side retrofit story
 * wires the running Stryker version through (#1908).
 *
 * Higher score = better. New paths land in the `additions` bucket
 * (Story #2012 — any real-world score under 100 must never flip to a
 * regression); removed paths count as improvements when their score was
 * non-perfect. Scaffold is generated by `makeBaselineKind` (Story #3983).
 *
 * ## Rollup weighting (Story #5058)
 *
 * The rollup score is a **mutant-weighted** mean —
 * `sum(score_i * mutants_i) / sum(mutants_i)`, where
 * `mutants_i = killed_i + survived_i`. It used to be `scoreSum / rows.length`,
 * an unweighted mean over files, under which a 3-mutant file carried the same
 * weight as a 300-mutant one: adding a handful of thinly-mutated new files
 * dragged the whole-repo number down far enough to breach the floor arm while
 * the compare arm reported no regression at all (a newly-scanned file has no
 * baseline row, so it can only move the aggregate `applyFloors` scores).
 *
 * Both weights are already summed in the same loop and are already required
 * by the row schema, which is `additionalProperties: false` — so the weighted
 * score is computable from the existing row shape with no producer change and
 * no schema change.
 *
 * **Limit of the approximation.** Rows carry no timeout or no-coverage counts
 * (`noCoverage` in the rollup is hardcoded `0`), so `killed + survived` is not
 * Stryker's full mutant population wherever timed-out or uncovered mutants
 * exist. The weighted score therefore *approximates* Stryker's published
 * overall score — it does not reproduce it. Closing that gap needs a producer
 * change and its own Story.
 *
 * Because this changes what the stored number MEANS, it is a semantics
 * migration: a baseline measured at 88.51 unweighted is 85.18 weighted over
 * the same rows, so every floor calibrated on the old mean breaches on
 * upgrade. `assertBaselineCompatible` below fails such a baseline closed —
 * a bare `kernelVersion` bump would not, because `kernelMatch` feeds only the
 * reporting-side drift count and reaches no exit code.
 */

import { canonicalise } from '../path-canon.js';
import { makeBaselineKind } from './kind-factory.js';

export const name = 'mutation';
export const keyField = 'path';

/**
 * Kernel version of the mutation scorer. Bumped off the original `1.0.0` by
 * Story #5058: the rollup score changed from an unweighted file mean to a
 * mutant-weighted mean, so rows stamped below this version were aggregated
 * under superseded semantics.
 */
const KERNEL_VERSION = '2.0.0';

/** Major of {@link KERNEL_VERSION} — the weighted-rollup boundary. */
const WEIGHTED_ROLLUP_MAJOR = 2;

const RESEED_REMEDY =
  'Re-seed the baseline: re-run this project mutation run (Mandrel ships no ' +
  "runner — Stryker is the upstream producer, e.g. 'npx stryker run') so " +
  "'baselines/mutation.json' is rewritten under the weighted rollup, then " +
  "commit it with a 'baseline-refresh:' subject and recalibrate the gate's " +
  'floors against the new number.';

export function projectRow(row) {
  return {
    path: canonicalise(row.path),
    score: Number(row.score),
    killed: Number(row.killed ?? 0),
    survived: Number(row.survived ?? 0),
  };
}

/**
 * Parse the major component of a semver-ish stamp.
 *
 * @param {unknown} version
 * @returns {number|null} The major, or null when unparseable/absent.
 */
function majorOf(version) {
  const match = /^(\d+)\./.exec(String(version ?? ''));
  return match ? Number(match[1]) : null;
}

/**
 * Kind-module hook (Story #4775) — refuse a loaded baseline whose rollup was
 * aggregated by the superseded unweighted mean. `checkBaselineSemantics`
 * dispatches here and `check-baselines`' evaluate phase turns a non-null
 * return into a fail-closed `semantics` schema error, so a pre-weighting
 * baseline can never be silently scored against floors calibrated on a
 * different definition of the number. Follows the `kinds/crap.js` precedent.
 *
 * An absent or unparseable stamp is rejected too: `kernelVersion` is required
 * by the shared envelope schema, so its absence is not evidence of a newer
 * writer.
 *
 * @param {object|null} baseline A loaded v2 baseline envelope.
 * @returns {string|null} Operator-facing message, or null when compatible.
 */
export function assertBaselineCompatible(baseline) {
  if (!baseline) return null;
  const stamped = baseline.kernelVersion ?? null;
  const major = majorOf(stamped);
  if (major !== null && major >= WEIGHTED_ROLLUP_MAJOR) return null;
  return (
    `[mutation] rollup scoring semantics changed: baseline=${stamped ?? '<unstamped>'} ` +
    `running=${KERNEL_VERSION}. The rollup score is now a mutant-weighted mean ` +
    '(sum(score * mutants) / sum(mutants)) rather than an unweighted mean over ' +
    'files, so the stored aggregate is a different number for the same rows and ' +
    `the floors calibrated against it no longer mean what they did. ${RESEED_REMEDY}`
  );
}

/**
 * A row's mutant count — the weight it carries in the rollup score.
 *
 * @param {object} row
 * @returns {number}
 */
function mutantsOf(row) {
  return (row.killed ?? 0) + (row.survived ?? 0);
}

/**
 * Sum one numeric row field across a row set.
 *
 * @param {object[]} rows
 * @param {string} field
 * @returns {number}
 */
function sumOf(rows, field) {
  let total = 0;
  for (const r of rows) total += r[field] ?? 0;
  return total;
}

/**
 * The mutant-weighted mean score: `sum(score * mutants) / sum(mutants)`.
 *
 * Zero-mutant guard: an empty row set, or one whose rows carry only zeroes,
 * has no weight to divide by. Returning 0 rather than dividing keeps `NaN` and
 * `Infinity` out of the envelope, where they would fail the schema's numeric
 * bounds downstream.
 *
 * @param {object[]} rows
 * @param {number} mutants Total mutant count across `rows`.
 * @returns {number}
 */
function weightedScore(rows, mutants) {
  if (mutants <= 0) return 0;
  let weighted = 0;
  for (const r of rows) weighted += (r.score ?? 0) * mutantsOf(r);
  return Number((weighted / mutants).toFixed(2));
}

/**
 * Aggregate rows into the rollup shape. `killed` and `survived` stay plain
 * sums and `noCoverage` stays hardcoded 0 — the weighting changes `score`
 * alone.
 *
 * @param {object[]} rows
 * @returns {{score: number, killed: number, survived: number, noCoverage: number}}
 */
function aggregate(rows) {
  const scored = rows ?? [];
  const killed = sumOf(scored, 'killed');
  const survived = sumOf(scored, 'survived');
  return {
    score: weightedScore(scored, killed + survived),
    killed,
    survived,
    noCoverage: 0,
  };
}

export const {
  kernelVersion,
  sortRows,
  rollup,
  compare,
  applyEpsilon,
  mergeRows,
} = makeBaselineKind({
  keyField,
  kernelVersion: KERNEL_VERSION,
  axes: ['score'],
  betterWhen: 'higher',
  aggregate,
  missingBasePolicy: 'addition',
  removedRowPolicy: {
    kind: 'improvement-when',
    when: (b) => (b.score ?? 0) < 100,
  },
});
