/**
 * kinds/mutation.js — per-kind module for the mutation-testing baseline
 * (Story #1891). Row shape: `{ path, score, killed, survived }`. Rollup
 * carries score/killed/survived/noCoverage. Stryker is the upstream
 * kernel; we pin a static `1.0.0` until a Mandrel-side retrofit story
 * wires the running Stryker version through (#1908).
 *
 * Higher score = better. New paths land in the `additions` bucket
 * (Story #2012 — any real-world score under 100 must never flip to a
 * regression); removed paths count as improvements when their score was
 * non-perfect. Scaffold is generated by `makeBaselineKind` (Story #3983).
 */

import { canonicalise } from '../path-canon.js';
import { makeBaselineKind } from './kind-factory.js';

export const name = 'mutation';
export const keyField = 'path';

export function projectRow(row) {
  return {
    path: canonicalise(row.path),
    score: Number(row.score),
    killed: Number(row.killed ?? 0),
    survived: Number(row.survived ?? 0),
  };
}

function aggregate(rows) {
  if (!rows || rows.length === 0) {
    return { score: 0, killed: 0, survived: 0, noCoverage: 0 };
  }
  let scoreSum = 0;
  let killed = 0;
  let survived = 0;
  for (const r of rows) {
    scoreSum += r.score ?? 0;
    killed += r.killed ?? 0;
    survived += r.survived ?? 0;
  }
  return {
    score: Number((scoreSum / rows.length).toFixed(2)),
    killed,
    survived,
    noCoverage: 0,
  };
}

export const {
  kernelVersion,
  sortRows,
  rollup,
  compare,
  applyEpsilon,
  mergeRows,
} = makeBaselineKind({
  keyField,
  kernelVersion: '1.0.0',
  axes: ['score'],
  betterWhen: 'higher',
  aggregate,
  missingBasePolicy: 'addition',
  removedRowPolicy: {
    kind: 'improvement-when',
    when: (b) => (b.score ?? 0) < 100,
  },
});
